sitenow_articles.settings:
  type: config_object
  label: 'SiteNow Articles settings'
  mapping:
    featured_image_display_default:
      type: string
      label: Featured image display default
    tag_display_type:
      type: string
      label: Tag display default
