adding:
  dependencies:
    config:
      - node.type.writing
      - taxonomy.vocabulary.writing_collection
    module:
      - content_translation
  permissions:
    - 'create content translations'
    - 'create terms in writing_collection'
    - 'create writing content'
    - 'delete own writing content'
    - 'delete writing revisions'
    - 'edit any writing content'
    - 'edit own writing content'
    - 'edit terms in writing_collection'
    - 'enter writing revision log entry'
    - 'override writing published option'
    - 'revert writing revisions'
    - 'translate writing node'
    - 'translate writing_collection taxonomy_term'
    - 'view writing revisions'
removing: {  }
