adding:
  dependencies:
    config:
      - node.type.lockup
      - workflows.workflow.lockup
  permissions:
    - 'create lockup content'
    - 'edit any lockup content'
    - 'edit own lockup content'
    - 'enter lockup revision log entry'
    - 'use lockup transition create_new_draft'
    - 'use lockup transition needs_review'
removing: {  }
