adding:
  dependencies:
    config:
      - field.field.node.event.field_event_locations
  content:
    field_event_locations:
      type: entity_reference_autocomplete
      weight: 26
      region: content
      settings:
        match_operator: CONTAINS
        match_limit: 10
        size: 60
        placeholder: ''
      third_party_settings: {  }
removing: {  }
