sitenow_pages.settings:
  type: config_object
  label: 'SiteNow Pages settings'
  mapping:
    featured_image_display_default:
      type: string
      label: Featured image display default
    tag_display_type:
      type: string
      label: Tag display default
