sitenow_people.person_type.*:
  type: config_entity
  label: Person Type
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
    allow_former:
      type: boolean
    allowed_fields:
      type: sequence
      label: 'Allowed fields'
      sequence:
        type: string
    tag_display_type:
      type: string
      label: Tag display default
sitenow_people.settings:
  type: config_object
  label: 'SiteNow People settings'
  mapping:
    tag_display_type:
      type: string
      label: Tag display default
